[[stack]]
name = "dns-deployment-home"
tags = ["dns", "instance"]
[stack.config]
server = "dns-server"
git_account = "b-"
repo = "b-/dns-deploy"
reclone = true
file_paths = ["compose.yaml"]
extra_args = ["--remove-orphans"]
environment = """
DNS_SERVER_ADMIN_PASSWORD=[[OP__KOMODO__TECHNITIUM_DNS__PASSWORD]]
TS_AUTHKEY = [[OP__KOMODO__TAILSCALE_OP__CLIENT_SECRET]]?ephemeral=true
"""