[[resource_sync]]
name = "dns-deploy-sync"
tags = ["dns", "sync"]
[resource_sync.config]
repo = "b-/dns-deploy"
git_account = "b-" 
resource_path = ["sync.toml"]
managed = true
delete = true
match_tags = ["dns", "sync"]

[[resource_sync]]
name = "dns-instances"
tags = ["dns", "instances"]
[resource_sync.config]
repo = "b-/dns-deploy"
git_account = "b-"
resource_path = ["deploy.toml"]
managed = true
delete = true
match_tags = ["dns", "instance"]
